import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_lib/header/header";
import Footer from "./_lib/footer/footer";
import { ErrorWrapper } from "./error-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: 'Next.js Tutorial',
    template: '%s | Abhishek'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <div style={{height: 'calc(100vh - 7.5rem)'}} className="flex items-center justify-center">
          <ErrorWrapper>
            {children}
          </ErrorWrapper>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
